apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: test-clamav-update-
spec:
  pipelineSpec:
    tasks:
      - name: create-clamav-db-artifact
        taskSpec:
          description: Downloads a database using a custom image and script, then uploads the result as a trusted artifact.
          params:
            - name: ociStorage
              type: string
            - name: runtimeImage
              type: string
            - name: executionScript
              type: string
          results:
            - name: DB_ARTIFACT
              type: string
          volumes:
            - name: workdir
              emptyDir: {}
          stepTemplate:
            volumeMounts:
              - mountPath: /var/workdir
                name: workdir
          steps:
            - name: update-db-data
              image: $(params.runtimeImage)
              workingDir: /var/workdir
              script: $(params.executionScript)
              computeResources:
                requests:
                  memory: 2Gi
                limits:
                  memory: 4Gi
            - name: create-trusted-artifact
              image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
              args:
                - create
                - --store
                - $(params.ociStorage)
                - $(results.DB_ARTIFACT.path)=/var/workdir/source
              computeResources:
                requests:
                  memory: 2Gi
                limits:
                  memory: 2Gi
        params:
          - name: ociStorage
            value: "quay.io/redhat-user-workloads/rh-ee-jcullina-tenant/poc-clamav-a39ad:latest"
          - name: runtimeImage 
            value: "quay.io/redhat-user-workloads/rh-ee-jcullina-tenant/poc-clamav-a39ad:3eeaf8a99fa66182f3ee14ce2345e9af4bf0ce01"
          - name: executionScript
            value: |
              #!/bin/sh
              set -ex
              DB_PATH="/var/workdir/source/clamav-db"
              mkdir -p "$DB_PATH"
              chmod -R 777 "$DB_PATH"
              freshclam --datadir="$DB_PATH"     
  taskRunTemplate:
    serviceAccountName: konflux-integration-runner

#8 Oct, working
