apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-clamav-db
spec:
  description: Downloads the ClamAV database and uploads it as a trusted artifact.
  params:
    - name: ociStorage
      type: string
      description: The OCI repository to store the artifact.
  results:
    - name: DB_ARTIFACT
      type: string
      description: The Trusted Artifact URI pointing to the new database artifact.
  volumes:
    - name: workdir
      emptyDir: {}
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: update-db-data
      image: "quay.io/redhat-user-workloads/rhtap-integration-tenant/poc-clamav-e111e:latest"
      workingDir: /var/workdir
      script: |
        #!/bin/sh
        set -ex
        DB_PATH="/var/workdir/source/clamav-db"
        mkdir -p "$DB_PATH"
        echo "Starting ClamAV database update..."
        freshclam --datadir="$DB_PATH"
        echo "ClamAV DB update complete."
      computeResources:
        requests:
          memory: 2Gi
        limits:
          memory: 4Gi

    - name: create-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
      args:
        - create
        - --store
        - $(params.ociStorage)
        - $(results.DB_ARTIFACT.path)=/var/workdir/source
      computeResources:
        requests:
          memory: 2Gi
        limits:
          memory: 2Gi
