apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: update-db-as-trusted-data
spec:
  description: Downloads a database using a custom image and script, then uploads the result as a trusted artifact.
  params:
    - name: ociStorage
      type: string
      description: The OCI repository where the Trusted Artifacts are stored (e.g., quay.io/your-team/trusted-artifacts).
    - name: runtimeImage
      type: string
      description: "The custom container image used to run the db update command (e.g., your clamav-updater)."
    - name: executionScript
      type: string
      description: "The script to execute inside the runtime image to update the database."
  results:
    - name: DB_ARTIFACT
      type: string
      description: The Trusted Artifact URI pointing to the newly created database artifact.
  volumes:
    - name: workdir
      emptyDir: {}
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: update-db-data
      image: $(params.runtimeImage)
      workingDir: /var/workdir
      script: $(params.executionScript)
      computeResources:
        requests:
          memory: 2Gi
        limits:
          memory: 4Gi

    - name: create-trusted-artifact
      image: quay.io/redhat-appstudio/build-trusted-artifacts:latest@sha256:9b180776a41d9a22a1c51539f1647c60defbbd55b44bbebdd4130e33512d8b0d
      args:
        - create
        - --store
        - $(params.ociStorage)
        # This takes the contents of the /var/workdir/source directory and packages it.
        # Your executionScript must save the database files into this directory.
        - $(results.DB_ARTIFACT.path)=/var/workdir/source
      computeResources:
        requests:
          memory: 2Gi
        limits:
          memory: 2Gi
